version: 2.1
jobs:
  build:
    resource_class: macos.m1.medium.gen1
    macos:
      xcode: "14.2.0"
    steps:
      - checkout
      - run: wget https://nightly.link/alanocallaghan/openslide-crossplatform-builds/workflows/jar/main/openslide-natives.zip
      - run: unzip openslide-natives.zip
      - run: echo 'export CLASSIFIER="darwin-aarch64"' >> $BASH_ENV
      - run: brew install openjdk@17
      - run: |
          wget --quiet https://openslide.cs.cmu.edu/download/openslide-testdata/Mirax/CMU-1.zip
          unzip CMU-1.zip
      - run: ./gradlew run --args="CMU-1.mrxs"


workflows:
  version: 2
  build:
    jobs:
      - build
