version: 2.1
resource_class: macos.m1.medium.gen1
jobs:
  build:
    macos:
      xcode: "14.2.0"
    steps:
      - checkout
      - run: wget https://nightly.link/alanocallaghan/openslide-cross-builds/actions/runs/6163791899/openslide-natives.zip
      - run: unzip openslide-natives.zip
      - run: brew install openjdk@17
      - run: ./gradlew run --args="CMU-1-Small-Region.tiff"

workflows:
  version: 2
  build:
    jobs:
      - build
