on: push

jobs:
  check:
    name: Check if openslide works
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with: 
          repo: alanocallaghan/openslide-winbuild
          workflow: main.yml
      - name: Unpack
        shell: bash
        run: |
          if [ "${{matrix.platform}}" == "ubuntu-latest" ]; then
            echo "ubuntu"
            tar -xf openslide-build-main/openslide-build-main/openslide-linux-x86_64-main.tar.gz
            echo "JNAPATH=openslide-build-main/openslide-build-main/openslide-linux-x86_64-main/lib/" >> $GITHUB_ENV
          elif [ "${{matrix.platform}}" == "macos-latest" ]; then
            echo "macos"
            tar -xf openslide-build-main/openslide-build-main/openslide-mac-x86_64-main.tar.gz
            echo "JNAPATH=openslide-build-main/openslide-build-main/openslide-mac-x86_64-main/lib/" >> $GITHUB_ENV
          elif [ "${{matrix.platform}}" == "windows-latest" ]; then
            echo "win"
            unzip openslide-build-main/openslide-build-main/openslide-win-x86_64-main.zip
            echo "JNAPATH=openslide-build-main/openslide-build-main/openslide-win-x86_64-main/lib/" >> $GITHUB_ENV
          fi
      - name: Sanity check
        shell: bash
        run: |
          echo $(tree .)
      - name: Run with Gradle
        run: ./gradlew run --args="CMU-1-Small-Region.tiff"
