on: push

jobs:
  check:
    name: Check if openslide works
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          repo: alanocallaghan/openslide-crossplatform-builds
          workflow: jar.yml
          name: openslide-natives
      - name: Set classifier
        shell: bash
        run: |
          if [ ${{matrix.platform}} == 'windows-latest' ]; then
            echo 'CLASSIFIER=win32-x86-64' >> $GITHUB_ENV
          elif [ ${{matrix.platform}} == 'macos-latest' ]; then
            echo 'CLASSIFIER=darwin-x86-64' >> $GITHUB_ENV
          else
            echo 'CLASSIFIER=linux-x86-64' >> $GITHUB_ENV
          fi
      - name: Download mrxs
        if: matrix.platform != 'windows-latest'
        shell: bash
        run: |
          wget --quiet https://openslide.cs.cmu.edu/download/openslide-testdata/Mirax/CMU-1.zip
          unzip CMU-1.zip
      - name: Run with Gradle
        shell: bash
        run: ./gradlew run --args="CMU-1.mrxs"
