on: push

jobs:
  check:
    name: Check if openslide works
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          repo: alanocallaghan/openslide-winbuild
          workflow: build.yml
          name: openslide-natives
      - name: Run with Gradle
        shell: bash
        run: ./gradlew run --args="CMU-1-Small-Region.tiff"
